export const validTypeRepositories = [
  'BD Liquibase',
  'Conecta Frontend',
  'docker ms',
  'Front - HTML',
  'Infra',
  'Java DataDog MS',
  'Java DataDog Profile MS',
  'Java Lamda',
  'Java Lamda Light',
  'Java Lib (Jfrog Gradle)',
  'Java MonoRepo MS',
  'Java MS',
  'Java OpenL',
  'Node DataDog MS',
  'Java OpenRules',
  'jira plugin',
  'lambda',
  'laravel',
  'liquibase',
  'node 12 lambda',
  'node 12 lambda edge',
  'node 12 lib (jfrog npm)',
  'node 12 microfrontend',
  'node 12 ms',
  'node 14 datadog ms',
  'node 14 lambda',
  'node 14 lambda light',
  'node 14 microfrontend',
  'node 14 monorepo ms',
  'node 14 ms',
  'Node Lambda',
  'Node Lambda Edge',
  'Node Lambda Light',
  'Node Lambda Mobile',
  'Node Lib (Jfrog NPM)',
  'Node Microfrontend',
  'Node Monorepo Microfrontend',
  'Node MonoRepo MS',
  'Node MS',
  'Python Lambda',
  'node ms microfrontend',
  'nodejs lambda',
  'php symfony',
  'Python MS',
  'Wordpress',
  'ssh guardian',
  'Infra terraform v1.5.6',
  'Java OpenL',
  'BD Liquibase',
  'Conecta Frontend2',
];
